### ISSUE TITLE
#INC-5312: Missing image

### ISSUE THREAD

**Issue by vanessa-cooper** [ObelusFamily/Anythink-Market-j7yb1#2]
Cool! Now, It seems that when creating a new product without an image, there are broken images showing up in the product catalog. Please fix this by replicating this bug locally with mock data.
Take a screenshot of the fix and attach it to a PR when you close the bug. There's a placeholder image in the repo that you can use named `placeholder.png`

**Comment by ppkinev** [comment]
<img width="771" alt="Screenshot 2022-07-08 at 18 07 38" src="https://user-images.githubusercontent.com/20816064/178019813-c02b4931-5d60-4c03-a156-87fed20e2d57.png">
